### ISSUE TITLE
Zigbee, есть ли вероятность поддержки?

### ISSUE THREAD

**Issue by almirus** [pvvx/THB2#2]
Добрый день, возможна ли поддержка в будущем Zigbee для https://pvvx.github.io/TH-05/

**Comment by pvvx** [comment]
Скорее всего нет. Или через неопределенное время, т.к. для данного чипа нет доступного SDK для Zigbee.

**Comment by almirus** [comment]
А тестовая прошивка bluetooth для TH05 сейчас шлет в эфир данные в "формате" АТС?

**Comment by pvvx** [comment]
Для TH05 пока ничего нет. Только [THB2](https://pvvx.github.io/THB2).

**Comment by almirus** [comment]
а, я успел обрадоваться и был готов шить. спасибо
