### ISSUE TITLE
THB2, I can't program. Error read Revision!

### ISSUE THREAD

**Issue by artur1702** [pvvx/THB2#21]
Hi,
As in Title. Linux operating system.
THB2 flashes once blue led, but ends with the error shown below and cannot be programmed.

python3 rdwr_phy62x2.py -p /dev/ttyUSB1 -e -r wh BOOT_THB2_v14.hex 
=========================================================
PHY62x2 Utility version 25.01.24
---------------------------------------------------------
Connecting...
PHY62x2 - Reset Ok
Error read Revision!

What can I do?

**Comment by pvvx** [comment]
| Adapter | Device |
|---|---|
| GND | -Vbat |
| +3.3В | +Vbat |
| TX | RX1 |
| RX | TX1 |
| RTS | RESET |

**Comment by pvvx** [comment]
RTS->RESET connected?

**Comment by pvvx** [comment]
What operating system do you have?
In Linux, character reception delays in USB-UART and much more do not work normally.
Try increasing self._port.timeout
https://github.com/pvvx/THB2/blob/master/rdwr_phy62x2.py#L227

**Comment by pvvx** [comment]
> Yes, I have been using only Linux for many years.

Linux hasn't been updated to new hardware standards in ten years. Including SSD and CPU. As a result, it is outdated and can only be used with outdated equipment, and even then not with all...

**Comment by 1500WK1500** [comment]
I had the same issue under linux. The problem was that RTS was toggled shortly when the serial connection gets closed and reopen again. I could fix it by removing the two lines which closed and reopen the serial connection for the baud rate change. 
`self._port.close() ` and `self._port.open()`
https://github.com/pvvx/THB2/blob/52e87b987b2f3fe7a5cc2916081ba5ae1b605b56/rdwr_phy62x2.py#L246C1-L248C21

As far as I know there is no need for closing the connection before changing the baud rate in pyserial.

**Comment by xyzzy42** [comment]
> I had the same issue under linux. The problem was that RTS was toggled shortly when the serial connection gets closed and reopen again.

This is controllable via the termios setting `HUPCL`.  When set, which is the default, it causes the serial port to "hang up" when the last process to have it open closes it.  This de-asserts RTS.  It can be turned off via the command:
```sh
stty -hupcl < /dev/ttyUSB0
```
With the correct port of course.

Or via python:
```python
port = serial.Serial(…);
import termios
attr = termios.tcgetattr(port.fileno())
attr[2] &= ~termios.HUPCL
termios.tcsetattr(port.fileno(), termios.TCSANOW, attr)
```

There is no need to close the port to change baud rates, but if output has been sent at the prior baud rate, `Serial.flushOutput()` should be called to insure all data is transmitted before changing the rate.  The rate change happens immediately and does not queue behind data already in the serial port's buffer.  Then call `Serial.flushInput()` *after* the rate change, to prevent reading any garbage data that was received and buffered at the incorrect baud rate before the rate changed.
