### ISSUE TITLE
Настройки при включении Boot загрузчика. (защита от дурака)

### ISSUE THREAD

**Issue by Balaganoff** [pvvx/THB2#25]
Ситуация. Прошил бут, прошил ота , все ок. Начал счелкать настройки. В итоге установил максимум (255сек ) интервал посылок и поменял имя.
Ну и я потерял устройство. Не находится. Так неохота опять выдергивать, плату чтобы стереть и перешить.
Как я понимаю защита от дурака, такого как я )) не предусмотрена и при загрузке в boot настройки в дефолтные не сбрасывает? 

И да ! Спасибо за отличную работу!

**Comment by froloffw7** [comment]
Загрузитесь в FW BOOTб как описано в [README](https://github.com/pvvx/THB2/blob/master/README.md#fw-boot-%D0%B8-ota) и заново выполните OTA.

**Comment by pvvx** [comment]
Выньте батарею и зажмите кнопку. Вставьте батарею. Должен загрузиться в boot. 
Нажатие кнопки меняет интервал на 1.6 сек для подключения

**Comment by Balaganoff** [comment]
nRFConnect соединяется с первого раза , подаю команду 56, при следующем обновлении уже другое значение. 
Пробовал и в boot и в обычном режиме и батарейку откидывал. 
Не видит chrome на смартфоне и все тут ((  Причем я именно с этого смартфона OTA прошивал. 
![photo1709101041](https://github.com/pvvx/THB2/assets/26416834/c6b6b93b-92cd-4dc6-a6e1-5243b06e5846)
![photo1709101041(1)](https://github.com/pvvx/THB2/assets/26416834/d660ac31-ae6a-485c-bd27-1e5c2d032084)

**Comment by pvvx** [comment]
Наверно в js [PHY62x2BTHome.html](https://pvvx.github.io/THB2/web/PHY62x2BTHome.html) стоит фильтр - не показывает устройства без имени... Надо поменять... Но это позже...

А пока введите '0100'  в сервис 0xFCD2 c характеристикой 0xFFF4. Сделает имя по умолчанию.

**Comment by Balaganoff** [comment]
> Наверно в js [PHY62x2BTHome.html](https://pvvx.github.io/THB2/web/PHY62x2BTHome.html) стоит фильтр - не показывает устройства без имени или с хитрыми символами... Надо поменять... Но это позже, т.к. может быть проблема в "Web Blouetooth API" у Chrome и ничего сделать не выйдет.
> 
> А пока введите `0100` в сервис 0xFCD2 c характеристикой 0xFFF4. Сделает имя по умолчанию.

Вот спасибо ! Все поехало !

**Comment by pvvx** [comment]
Не выходит заставить  "Web Bluetooth API" сканировать устройства со всеми возможными именами (региональными символами). Но русские вписал:
		deviceOptions.filters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz_#@!*0123456789';,.<>{}[]абвгдеёжзийклмнопрстуфхцчшщъыьэюяАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ"
Т.е. только символ из списка может быть первым для того, чтобы Chrome нашел устройство.

![image](https://github.com/pvvx/THB2/assets/12629515/4be862b8-ae2c-4126-966f-794aa6a3ae9d)

![image](https://github.com/pvvx/THB2/assets/12629515/9b2852d8-378f-47fd-8ae7-82a7db4782cd)

Если есть какие другие варианты исправить фильтр сканирования в  "Web Bluetooth API" - напишите как.

**Comment by almirus** [comment]
@pvvx позвольте мини оффтоп, а что за устройства с именем TY у меня в кв они тож есть (наверняка соседские)?

**Comment by pvvx** [comment]
Обычно это Tuya WiFi розетки. Они настраиваются по BLE, если там не ESP82xx. В таких розетках всё работает и по BLE и по WiFi. Но это никого из "писателей" Умных домов не интересует. 
Таким розеткам не обязательно соединение с Cloud Tuya при включении в сеть, в отличии от розеток сделанных на ESP чипе.
