### ISSUE TITLE
Can it be set to Farenheit (on the display?)

### ISSUE THREAD

**Issue by NeoMatrixJR** [pvvx/THB2#28]
Any way to set a TH05 to Farenheit for those of us who are global unit challenged?  At least for the display?

**Comment by HumbleDeer** [comment]
The code implies this should be possible. https://github.com/pvvx/THB2/blob/f9649f8437d029ee9cce966f4b637054d630be6a/bthome_phy6222/source/lcd_th05.c#L81

**Comment by pvvx** [comment]
Config -> Option: Show Temperature in Fahrenheit
In ver 1.8 beta
