### ISSUE TITLE
Incorrect temperature value if actual temperature is above 41 degrees Celsius

### ISSUE THREAD

**Issue by Deoptim** [pvvx/THB2#39]
BOOT_BTH01_v16
BTH01_v16

The BTH01 sensor is mounted outside on the glass. Due to the fact that it warms up in the sun (it would be good to install it in the shade) it warms up above 41-42 degrees Celsius.
But as soon as this temperature threshold is exceeded, the sensor shows about -122 degrees.

<img src="https://github.com/pvvx/THB2/assets/5656726/b7b9bb8e-354a-4685-a169-96a799234fb2" width="300">

**Comment by pvvx** [comment]
Fixed in version 1.7.
