### ISSUE TITLE
COM11 not found

### ISSUE THREAD

**Issue by francodutch** [pvvx/THB2#55]
serial port issue when flashing

Thanks for your work on this. I'm trying to flash TH5F, but when running the Python script (on a Mac) I run into:

> =========================================================
> PHY62x2 Utility version 11.03.24
> ---------------------------------------------------------
> Error: Open COM11, 9600 baud! Error: [Errno 2] could not open port COM11: [Errno 2] No such file or directory: 'COM11'

The serial port that is opened is the UNIX type (/dev/tty.usbserial-A50285BI - ) aren't COM ports Windows only? Should this work on a Mac?

**Comment by pvvx** [comment]
python3 rdwr_phy62x2.py -p /dev/tty.usbserial-A50285BI -e -r wh BOOT_xxx_vxx.hex
