### ISSUE TITLE
“TH05” with QD01 2340 NT

### ISSUE THREAD

**Issue by Nanganator** [pvvx/THB2#60]
I just received 2X “TH05” devices with the TH05F board layout but with the QD01 2340 NT chip on them. Is the QD01 2332 NT firmware compatible with this chip?
![20240703_103538_Original](https://github.com/pvvx/THB2/assets/64145564/66c18da6-5afc-471e-932e-50b696f2f639)
![20240703_104457_Original](https://github.com/pvvx/THB2/assets/64145564/f42077c4-e503-4b1d-8ade-934778c01046)
![original_3a9130c9-ec1c-4120-b486-adfe09ba6357_20240703_104528_Original](https://github.com/pvvx/THB2/assets/64145564/5c1399f7-51ac-4cdd-9d57-f4e2d6cea6bc)

**Comment by pvvx** [comment]
The type is determined by the display. By smiley symbol.
https://pvvx.github.io/TH-05/ or https://pvvx.github.io/TH05F/

**Comment by Nanganator** [comment]
Could it perhaps be some kind of new combination. It has the smiley face of the TH05 like this one:
![IMG_0172](https://github.com/pvvx/THB2/assets/64145564/71d0764b-9768-4e0d-825a-7c4059b5b317)
But flashing the TH05_v17.bin firmware makes the display stop working. All other functions are working.

**Comment by pvvx** [comment]
The printed circuit board is clearly different - from TH05F.
We need to try the TH05F firmware.
