### ISSUE TITLE
Support for TH08B

### ISSUE THREAD

**Issue by diwilli** [pvvx/THB2#75]
Are there any plans to support the TH08B?

happy to donate one to a developer if needed.

https://a.aliexpress.com/_EG4rnLR

**Comment by pvvx** [comment]
> https://a.aliexpress.com/_EG4rnLR

1. By link - is not delivered to my address.
2. Is WiFi, not Bluetooth.
3. Chipset is unknown.

---

I can order a zigbee option for research:
![image](https://github.com/user-attachments/assets/29872926-3ac2-40a8-a419-d31c6041aa04)

**Comment by diwilli** [comment]
Ah, yes you're right.  Sorry completely missed it was WiFi/Zigbee only.

Feel free to close.  Still happy to fund one if you're interested.

**Comment by pvvx** [comment]
Thank you, but I do not accept donations.
