### ISSUE TITLE
TH05Y_v3.1 with TH05_V1.4 screen - TEMPERATURE/HUMIDITY not working

### ISSUE THREAD

**Issue by Pinni3** [pvvx/THB2#84]
Flashed the unit(s) did try the firmwares BOOT_TH05_vNN.hex And **BOOT_TH05F_vNN.hex**
Is a **TH05_V1.4 screen** with the marking **TH05Y_v3.1** on pcb , chipset is **QD01 2340 NT CJT 3353C**
After OTA No screen nor TEMP or humidity info , battery is displayed 
![image](https://github.com/user-attachments/assets/7b6d5165-2412-44e9-8240-65379e66494e)
![image](https://github.com/user-attachments/assets/483fad7f-b3f7-4fb8-b467-81c33bd3c579)

**BOOT_TH05F_v18.hex** is running atm but still no data for temp and humidity 
![image](https://github.com/user-attachments/assets/a13035a9-2c81-4ad8-9550-d7331fa6ea3c)
![image](https://github.com/user-attachments/assets/427819ca-9d61-43b2-a05d-dcdb41d4f7bb)

Is there a new firmware needed or coud this be adjusted with actions from my side?

**Comment by pvvx** [comment]
> Is a TH05_V1.4 screen with the marking TH05Y_v3.1 on pcb 

Perhaps this is a new version of the printed circuit board and the sensor layout is done on other Soc pins.

**Comment by Pinni3** [comment]
How can i help in getting this on track ?
Pictures , measurements ?

**Comment by Pinni3** [comment]
![IMG_4259](https://github.com/user-attachments/assets/15456130-2d83-4170-a6db-ffb1ad3474c5)
![IMG_4258](https://github.com/user-attachments/assets/9cd93857-3267-4fa0-a0b2-e0bf6b655284)

**Comment by pvvx** [comment]
PCB layout is different from TH05Y_v1.1/v1.2

**Comment by tomasz-kos** [comment]
Hi, I have the same device. On my device temperature sensor is CHT8320 (marking ML). From datasheet I got that it uses 0x88 I2C address which after short checking isn't use in that code. As I have few of these devices I will try to log I2C communication on not reprogrammed device.

**Comment by Pinni3** [comment]
![Afbeelding van WhatsApp op 2024-11-20 om 15 32 10_618c1530](https://github.com/user-attachments/assets/7a987bdd-3ba0-498e-b79f-48e9f7a10f61)

**Comment by pvvx** [comment]
Sensylink 
| Order PN | Address | Accuracy | Green1 | Package | Marking ID2 | Packing | MPQ | Operation Temperature
|-- | -- | -- | -- | -- | -- | -- | -- | --|
|CHT8320ADNR | 0x88 | ±0.1℃±2.0%RH | Halogen free | DFN2X2-4 | MLYWXA | Tape & Reel | 3,000 | -40℃~+125℃

https://en.sensylink.com/html/web/product/wsdcgq/cwsdcgq/1694267611119996930.html

Datasheet does not describe how to work with it via I2C.
https://en.sensylink.com/upload/1/net.sensylink.portal/1717568489156.pdf

**Comment by Pinni3** [comment]
If you need testing or firmware extract just let me know.

**Comment by Pinni3** [comment]
> Right now Google only finds these descriptions: [CHT8310 Advanced Datasheet Ver1.1 20230927.pdf](https://github.com/pvvx/pvvx.github.io/blob/master/THB2/CHT8310%20Advanced%20Datasheet%20Ver1.1%2020230927.pdf) [CHT8315 Advanced Datasheet Ver1.6 20230927.pdf](https://github.com/pvvx/pvvx.github.io/blob/master/THB2/CHT8315%20Advanced%20Datasheet%20Ver1.6%2020230927.pdf) [CHT8305C Advanced Datasheet Ver2.5 2021-10-26.pdf](https://github.com/pvvx/pvvx.github.io/blob/master/THB2/CHT8305C%20Advanced%20Datasheet%20Ver2.5%202021-10-26.pdf)
> 
> (https://www.elektroda.com/rtvforum/viewtopic.php?p=21106861#21106861)
> 
> Copied to github...

I see but none of them is the same shape as the one used in the model i have picture of.
Shape is the same as in the non advanced pdf

**Comment by pvvx** [comment]
> I see but none of them is the same shape as the one used in the model i have picture of.
> Shape is the same as in the non advanced pdf

To work with CHT8320 (mark "ML"), you need a description of the I2C protocol and coefficients for calculating temperature and humidity. But they are not in the shortened datasheet from the Sensylink website.

**Comment by Pinni3** [comment]
I have checked on wechat, no extra documentation contact was only mail even via wechat.
I did send them (support) a mail, hoping on a reply from them.

**Comment by pvvx** [comment]
Test firmware
[TH05F_v19_test.zip](https://github.com/user-attachments/files/17834257/TH05F_v19_test.zip)

Sensor ID unknown.
Run Service->Command with parameter "05" and publish the response from the log.

**Comment by Pinni3** [comment]
18:39:50: Command response (05): ffffffff44
Also => Humidity is now 99%
![Afbeelding van WhatsApp op 2024-11-20 om 18 41 10_994c5dcf](https://github.com/user-attachments/assets/c9230ac4-e8b5-41bf-a125-8c771fc8ff9c)

**Comment by Pinni3** [comment]
**TH05F_v19t2.bin :**
![image](https://github.com/user-attachments/assets/4432424c-8c83-44b8-a4dd-85f715bc11d3)
![image](https://github.com/user-attachments/assets/9d8d1750-0b14-4e15-a5b4-af12d77cda00)
![image](https://github.com/user-attachments/assets/0ea8d1bb-c4c0-48c9-b641-400eefe23a14)

**Comment by Pinni3** [comment]
[divadiow] from the [Elektroda forum](https://www.elektroda.com/rtvforum/viewtopic.php?p=21106861#21106861) is also asking from his side.
Lets hope on some quick emails with the advanced info in PDF

**Comment by tomasz-kos** [comment]
If that helps, I2C communication with official software and monitor by phone (from power on and next 7 measurement every few seconds:
write to 0x44 ack data: 0x37 0x81 
read to 0x44 ack data: 0x59 0x59 0x53
write to 0x44 ack data: 0x24 0x00 
read to 0x44 ack data: 0x64 0x69 0x64 0x76 0x0E 0xFF
write to 0x44 ack data: 0x24 0x00 
read to 0x44 ack data: 0x64 0x34 0x56 0x77 0x5C 0x17
write to 0x44 ack data: 0x24 0x00 
read to 0x44 ack data: 0x63 0xF7 0xEC 0x78 0x2D 0x47
write to 0x44 ack data: 0x24 0x00 
read to 0x44 ack data: 0x63 0xDC 0x80 0x78 0x21 0x3A
write to 0x44 ack data: 0x24 0x00 
read to 0x44 ack data: 0x64 0xFE 0xCA 0x79 0xF7 0x6C
write to 0x44 ack data: 0x24 0x00 
read to 0x44 ack data: 0x6A 0xF8 0x01 0xCC 0x85 0x10
write to 0x44 ack data: 0x24 0x00 
read to 0x44 ack data: 0x66 0x97 0x20 0x93 0x70 0x19

Measurement shown on phone:
23.6 46
23.5 46
23.3 46
23.2 46
24 47
28.1 79
25.1 57

**Comment by Pinni3** [comment]
[CHT832X Advanced  Datasheet Ver1_NO-watermark.pdf](https://github.com/user-attachments/files/17840405/CHT832X.Advanced.Datasheet.Ver1_NO-watermark.pdf)

Hope this contains the info you need.

**Comment by pvvx** [comment]
[TH05F_v19t3.zip](https://github.com/user-attachments/files/17853301/TH05F_v19t3.zip)

**Comment by Pinni3** [comment]
Think wrong IC2 adress ? 
![image](https://github.com/user-attachments/assets/909eba77-b1fd-446b-9d5b-bc357962456b)


![image](https://github.com/user-attachments/assets/ff45d5ea-452a-4b8d-bb71-10aa25c23472)
and if needed the 05 service responce
![image](https://github.com/user-attachments/assets/11cdabf9-77cc-4229-975e-8983fba6fa6b)

**Comment by pvvx** [comment]
I don't have a TH05Y v3.1 thermometer and I don't have the ability to check the firmware for all sensor variants. There are already 4 sensor types to service, plus subtypes... Polling different types during initialization can cause some sensors to fail... It is necessary to select the polling sequence by types during initialization, etc.

I'll try to make another version later...

**Comment by Pinni3** [comment]
I understand the situation.
If i knew where to start and modify i would certainly help.
But i am clueless atm.

Just for identification purposes and other people (to be temporary warned) the came from this shop:
[RightSitu Official Store](https://www.aliexpress.com/store/1102474203?sortType=bestmatch_sort)
This[ item](https://nl.aliexpress.com/item/1005005234497671.html?spm=a2g0o.order_list.order_list_main.47.4cce79d2mB8XMP&gatewayAdapt=glo2nld)

If you need any help testing, etc just let me know ;-)

**Comment by pvvx** [comment]
Apparently, the sensor did not respond to the MID query command, since other types were polled before and this confused it...

**Comment by pvvx** [comment]
[TH05F_v19t4.zip](https://github.com/user-attachments/files/17867690/TH05F_v19t4.zip)

**Comment by Pinni3** [comment]
i think we have a winner!
10:21:54: Commandoreactie (05): 5959832044
![image](https://github.com/user-attachments/assets/7b28932b-a24e-49a3-b1ef-c3affb5376e7)
![image](https://github.com/user-attachments/assets/73da9cd9-2247-4e24-9abd-6b8bfab4885d)
![image](https://github.com/user-attachments/assets/e39b11c5-2831-4659-a3fe-e23f947bfbcc)

**Comment by Pinni3** [comment]
So sensor is working, now just letting it sit next to original FW that came straight out of the packaging.
Waiting to see if there is a big difference.
Will let them sit for 1 or so and check back in.
![Afbeelding van WhatsApp op 2024-11-22 om 10 29 41_4329d5b3](https://github.com/user-attachments/assets/0d685a22-ea07-49de-8dbe-d39b45af1b0f)

**Comment by Pinni3** [comment]
After 1 hour temps settled in and i can say it looks good!
![Afbeelding van WhatsApp op 2024-11-22 om 10 29 41_4329d5b3](https://github.com/user-attachments/assets/8fd31739-505d-4428-9f5f-a2de7ace1b02)
Any more changes needed ?  because it is working fine now.
Thank you for the help!

**Comment by pvvx** [comment]
It is necessary to measure average and peak consumption. Mainly duration of activity and what the sensor consumes - what contributes to the total consumption. The documentation does not clearly describe when the CHT832x sensor goes into sleep mode. It is advisable to do all measurements using PowerProfiler, not a tester... That is, a professional approach to measurement is needed...

**Comment by pvvx** [comment]
[Version 2.0(beta) published.](https://github.com/pvvx/THB2)

**Comment by tomasz-kos** [comment]
Hi,
I measured current with power profiler:
- average vith 5s update is 20uA (display enabled but not connected)
- sleep/idle about 14uA (as above) about 10uA with display disabled
- max for BT transmision about 22mA

I noticed 2 things:
- in normal mode BT transmission is every 5s (ok) but I2C communication is also every 5s once make conversion once read value, but in connected mode I2C is only every 10s - I assume that is expected behaviour
- I tried changing TX power but for all settings current for BT transmision is the same

**Comment by pvvx** [comment]
> in normal mode BT transmission is every 5s (ok) but I2C communication is also every 5s once make conversion once read value, but in connected mode I2C is only every 10s - I assume that is expected behaviour

The measurement interval is set in BLE advertising periods.
Before the last advertising period, the sensor starts measuring - a measurement command is transmitted. 
In the next SoC activity cycle (after last advertising period) measurements are read from the sensor.

**Comment by norbiv8** [comment]
Hi, my device just arrived, quickly flashed the latest FW. Measurement attached. The consumtion is pretty good IMHO.
![ppk-20241122T165705](https://github.com/user-attachments/assets/16448493-e0c5-4abd-bb1b-a032e6bec1d6)

**Comment by pvvx** [comment]
10uA in sleep mode is a lot.
The main reason is Tuya - A high-power LCD driver chip is installed.

Normal consumption during sleep for thermometers with CR2032 is up to 6 μA. At the same time, the average, measured over several BLE periods and multiples of them, is no more than 14 μA. Otherwise, CR2032 will not work for even 8 months.

**Comment by newwolf** [comment]
How did you flashed this version of the device?
Because I also received 1 this week and tried it the bleutooth methode and at the moment with 2 different usb connection on rx-tx and rx2-tx2 but still getting:
=================================
PHY62x2 Utility version 11.03.24
---------------------------------------------------------
Connecting...
PHY62x2 - Error Reset!
Check connection TX->RX, RX<-TX, RTS->RESET and Chip Power!

**Comment by Pinni3** [comment]
Set the RST-RESET connection also.
if you use the script adjust to the correct COM port that u are using.

**Comment by newwolf** [comment]
Did that also and it resets because when connecting the screen when connected it resets.
Also twisted the pins no-go.
Maybe both are not working correct but also use them for esp32 etc.

**Comment by tomasz-kos** [comment]
> If this is PowerProfiler II from nRF, then these are emissions from the range switch of the measurement circuit. In reality, there are peaks of about 8 mA (RF TX +0 dBm). These nRF glitches do not significantly affect the average measurement. But they distort the current picture. 

Yes I'm using Power Profiler Kit II and I'm doing that in my normal job (design battery operated sensors). I don't understand your  current graphs - I would suspect that measuring tool is broken.

My graphs:
10s measurement:
![image](https://github.com/user-attachments/assets/e3a0a88e-cbec-44b9-8e14-014414a28c4b)

Zoom to transmision wakeup:
![image](https://github.com/user-attachments/assets/9aedc4b9-b4a1-40df-8ead-375b20d4b25f)

Sleep current:
![image](https://github.com/user-attachments/assets/bc037c80-1286-4f64-9240-3792ba1e5020)


Based on my experience with BT development that graft of current for transmission are correct (as 3 advertisement transmision on channels 37, 38 and 39)

**Comment by pvvx** [comment]
Noted artifacts PowerProfiler II:

![image](https://github.com/user-attachments/assets/3d189367-adc0-45f4-b145-fb911200f7ed)

Real TH05Y_V1
![image](https://github.com/user-attachments/assets/e3898282-9e72-4c9d-9d9c-eae3dde9e197)
On the simplest meter, INA226:
![image](https://github.com/user-attachments/assets/48cda4d7-3e7b-4a0b-9886-1d2007337b56)

**Comment by pvvx** [comment]
TX RF ~ 6 mA
![image](https://github.com/user-attachments/assets/bf0d6cec-79cf-4fc8-9cab-7f702011164b)

Operation of the built-in PHY6222 DC-DC:
![image](https://github.com/user-attachments/assets/448a8aa5-3004-4924-ba35-e86e03df7f3c)

**Comment by tomasz-kos** [comment]
> This is a measurement of the linearly increasing current signal on PPII from a precision generator (>24 bits linearity). [#84 (comment)](https://github.com/pvvx/THB2/issues/84#issuecomment-2494335946)

Thank you for explanation, now I understand.

**Comment by pvvx** [comment]
Next, let's look at what distortions PPK2 introduces:
![image](https://github.com/user-attachments/assets/4adb3162-de06-4028-9038-01a715b1452e)
This is the current at the output of PPK2, with the range switch in PPK2:
![image](https://github.com/user-attachments/assets/1e92a050-35d7-4a73-a0d2-2666fe8673c6)

**Comment by paule999** [comment]
It looks like I have this particular variant.  I originally used BOOT_TH05_v19.hex &  TH05F_v19.bin and got the zerodisplay and came looking... saw that v20.bin fixes it (and it does) albeit temporarily before reverting to zeros shortly later. .. I'm guessing I need to replace boot firmware with v20 too... I notice there isn't currently a v20 OTA (update_boot) file available... is one likely or do I need to do it via uart again? 
Thanks for any help

**Comment by pvvx** [comment]
There are no changes in the BOOT_TH05_V20.HEX for TH05.
https://github.com/pvvx/THB2/tree/master/bin

**Comment by paule999** [comment]
Thank you for the reply! ...that's strange though... I tried using  BOOT_TH05_V20.HEX to update boot via OTA but kept getting "Inappropriate format of the firmware file size PHY6 OTA!" 

I assumed there was a different file for updating via OTA but there must be something else going on 😖.

**Comment by pvvx** [comment]
You need TH05**F**.

[TH05F](https://pvvx.github.io/TH05F) | BOOT_**TH05F**_vNN.hex | TH05F_vNN.bin | TH05Y_V1.1, TH05Y_V1.2, TH05Y_V3.1 (chip: QD01 2332 NT)
-- | -- | -- | --

Beta -version 2.0 has not yet been completed.
There will be changes.

The repository is upgraded.

**Comment by paule999** [comment]
> You need TH05**F**.
> [TH05F](https://pvvx.github.io/TH05F) 	BOOT_**TH05F**_vNN.hex 	TH05F_vNN.bin 	TH05Y_V1.1, TH05Y_V1.2, TH05Y_V3.1 (chip: QD01 2332 NT)
> 
> Beta -version 2.0 has not yet been completed. There will be changes.
> 
> The repository is upgraded.

Thank you very much for your time and effort with this! The F version you put up a little earlier worked perfectly. (Just in case you didn't know the smiley face is AWOL).... that's definitely not a criticism of any sort btw!... I'm very grateful you share all your hard work👍

**Comment by pvvx** [comment]
> (Just in case you didn't know the smiley face is AWOL) 

https://dictionary.cambridge.org/ru/%D1%81%D0%BB%D0%BE%D0%B2%D0%B0%D1%80%D1%8C/%D0%B0%D0%BD%D0%B3%D0%BB%D0%B8%D0%B9%D1%81%D0%BA%D0%B8%D0%B9/awol

PS: I don't speak English and it's difficult and time-consuming for me to describe everything through Google Translate - it doesn't understand Russian well.
