### ISSUE TITLE
ZTH05ZTU_V1.2 device support?

### ISSUE THREAD

**Issue by ccetin222222222222222222222222** [pvvx/THB2#86]
Hello, I have a tuya Zigbee thermometer I bought a year ago. It was having issues with z2m and ha, so I left it.

Screen looks the same as zth05 1.4, but the board looks a bit different.
![IMG_20241127_225801](https://github.com/user-attachments/assets/5679da6c-cba1-42e0-8b79-0d670863744d)
![IMG_20241127_225827](https://github.com/user-attachments/assets/8fd8e23a-c019-409d-b17a-a58fbbca4734)
![IMG_20241127_230106](https://github.com/user-attachments/assets/cf1c6d36-e950-4fdb-88db-3129c08f9a7c)

**Comment by pvvx** [comment]
It has a "Tuya MCU" chip installed.
This chip controls the LCD driver and sensor.
The firmware of the "ZTU" module will not change anything.

**Comment by ccetin222222222222222222222222** [comment]
That sucks. I was hoping to flash a new firmware to this device so I can use it at all with my ha, right now it's completely useless. I will probably just throw it out and buy a different module. 

Thank you for the help anyway

**Comment by pvvx** [comment]
https://pvvx.github.io/TS0601_TZE204/

**Comment by gomble** [comment]
> https://pvvx.github.io/TS0601_TZE204/
> 
> > I will probably just throw it out and buy a different module.
> 
> The сhinese from Tuya did this to sell it, and then the user will throw it in the trash.

does it work with the firmware here?

**Comment by pvvx** [comment]
https://github.com/pvvx/ATC_MiThermometer
+ [Modification for custom firmware](https://pvvx.github.io/TS0601_TZE204/)
