### ISSUE TITLE
How do I find out if it works?

### ISSUE THREAD

**Issue by bobybobybob** [pvvx/THB2#89]
How do I find out if it works?

My purchased sensor has the most similar layout to THB1 and THB3

THB1 and THB3 Firmeware works same...  maybe THB1 better??

With the web browser PHY62x2 BTHome I can establish a connection with Bluetooth and see the values for seconds, which then disappear again and no longer appear... unless I press the button and reconnect. 

In such a Youtube video, however, it can be seen that these values should be permanently visible

04:29:28: Searching for devices
04:30:34: Waiting for connection to THB3-A78721
04:30:37: Model: THB3
04:30:37: Firmware: github.com/pvvx
04:30:37: Hardware: 001A
04:30:37: Software: V1.9
04:30:37: Device info # hw: 001A, sw: 0019, services: 000043B8, sd: 0000
04:30:37: Connected.
04:30:41: Device is disconnected.

05:27:54: Waiting for connection to THB1-A51155
05:28:02: Device is disconnected.
05:28:02: NetworkError: GATT Server is disconnected. Cannot retrieve services. (Re)connect first with `device.gatt.connect`.
05:28:02: Reconnect 0 / 5
05:28:02: Waiting for connection to THB1-A51155
05:28:09: NetworkError: Connection Error: Connection attempt failed.
05:28:09: Reconnect 1 / 5
05:28:09: Waiting for connection to THB1-A51155
05:28:14: Model: THB1
05:28:14: Firmware: github.com/pvvx
05:28:14: Hardware: 0017
05:28:14: Software: V1.9
05:28:14: Device info # hw: 0017, sw: 0019, services: 000043B8, sd: 0000
05:28:14: Connected.
05:28:14: Set device time...
05:28:14: Set device time (23EEF34B67)...
05:28:18: Device is disconnected.

**The Pictures are Public Domain. You and other can use it free for your Homepage**

![d](https://github.com/user-attachments/assets/b9774251-09f1-41ab-96d5-e912aeb8b874)
![a](https://github.com/user-attachments/assets/8d580ae6-26b0-4ba3-8c7e-c3e05c9eeac8)
![b](https://github.com/user-attachments/assets/da0dde1d-518d-4dab-bc94-9ef88e1fe162)
![c](https://github.com/user-attachments/assets/27594b64-c10c-43b7-9cfc-8003618ddeff)
![e](https://github.com/user-attachments/assets/6532500d-9738-491e-93ba-9b75cb328db9)

The Pictures are Public Domain. You and other can use it free for your Homepage

**Comment by pvvx** [comment]
THB3 does not have a "BLE" icon on the screen.

**Comment by bobybobybob** [comment]
Thanks for the hint. I thought it was also there because the packaging also shows the symbol in the example pictures.
