### ISSUE TITLE
FYI: TH05Y_v3.1 2024-10-26 with new MCU QD01 2401 NT

### ISSUE THREAD

**Issue by rmoriz** [pvvx/THB2#90]
![52836811-DF1B-4A47-A4DF-9FCD15F4FCDF_1_201_a](https://github.com/user-attachments/assets/31a9cbbe-a8de-4a90-a8a4-d0c83d4d4ddb)
![4B8EB825-7ECB-40FA-89E4-B2195E2F3C15_1_201_a](https://github.com/user-attachments/assets/3e714afb-4665-48f4-b7ae-aacb09cb467f)
![IMG_7670](https://github.com/user-attachments/assets/1513d0d4-6158-4001-9c76-14b240f9529b)
![IMG_7671](https://github.com/user-attachments/assets/610926a6-31f0-4803-b0f6-6f5a43d71bc9)

QD01 **2401** NT

not yet tried to flash

**Comment by pvvx** [comment]
https://pvvx.github.io/TH05F/

**Comment by pvvx** [comment]
I don't see anything new in the specified device.
