### ISSUE TITLE
Error Flash Boot THB1

### ISSUE THREAD

**Issue by EMI2-2** [pvvx/THB2#93]
Hi, when I try to flash the boot, I get this error. The firmware backup, I have done well, but I can not put the boot:

#
$ python3 rdwr_phy62x2.py -p /dev/ttyUSB0 -e -r wh BOOT_THB1_v19.hex 
=========================================================
PHY62x2 Utility version 11.03.24
---------------------------------------------------------
Connecting...
PHY62x2 - Reset Ok
Revision: b'001364c8 6222M005'
FlashID: 1364c8, size: 512 kbytes
PHY62x2 - connected Ok
Traceback (most recent call last):
  File "/home/emi/THB1/rdwr_phy62x2.py", line 738, in <module>
    main()
  File "/home/emi/THB1/rdwr_phy62x2.py", line 663, in main
    hp = ParseHexFile(args.filename)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emi/THB1/rdwr_phy62x2.py", line 56, in ParseHexFile
    taddr = (int(hexstr[3:7],16))
             ^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 16: ''

I used:
lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm

**Comment by pvvx** [comment]
Please download the firmware file correctly.

**Comment by EMI2-2** [comment]
Thank you, but I don't understand.

I have downloaded BOOT_THB1_v19.hex and BOOT_THB1_v20.hex (Always the same error).

I have made a backup, installed the THB1_v19.bin firmware without errors, but the display is not showing. I have recovered the backup which is a bin and it works fine.

I think I have the problem with the .hex

What do I have to download again, my model is THB1.

regards

**Comment by EMI2-2** [comment]
SOLVED, thank you.
I got it, I downloaded all the code and not just the firmware.

Thank you very much.

**Comment by pvvx** [comment]
> I have downloaded BOOT_THB1_v19.hex and BOOT_THB1_v20.hex (Always the same error).

![image](https://github.com/user-attachments/assets/edacd242-29c4-4d91-a653-b37e041bde34)

**Comment by EMI2-2** [comment]
Thank you very much, everything works very well. Perfect.
