### ISSUE TITLE
Idea: raw screen acces

### ISSUE THREAD

**Issue by dakhnod** [pvvx/THB2#99]
Thanks for your great work on this!

It would be awesome if we could get raw access to the screen via BLE.
Here is a suggestion how we could send the data to a characteristic:
- byte 0-4: timeout in milliseconds (after this time the screen displays temperature and humidity again)
- byte 4-x: the screen data, one bit per screen segment

This way, we could render text to the LCD segments in the application, and just send the data to the screen!

What do you think?

**Comment by pvvx** [comment]
There is no idea here. Everything was planned long ago.

All firmwares have the "60" function.

"60xxxxxxxxxx" - output screen buffer to LCD.
The screen buffer contains a bitmap of LCD segments.
"60" - disable.

But so far only the TH05F firmware disables the measurement output when the "60" function is displayed on the screen.

The function "22" will be added in the next version. See the implementation https://github.com/pvvx/ATC_MiThermometer

**Comment by dakhnod** [comment]
Oh, my bad I didn't know.
I was thinking of includnig something like [gpioASM](https://github.com/dakhnod/gpioASM).
This would allow for setting a timeout for a bitmap.
Furthermore, this would allow for sending sequences of bitmaps, for example to have a longer text running on the screen.

Any thoughts on that?

**Comment by pvvx** [comment]
The LCD screen cannot display most letters. The LCD is designed to display numbers and a few symbols.

**Comment by dakhnod** [comment]
Okay, a few questions regarding this:
1. How can I set a timeout on a bitmap sent to the device?
2. How can I, after sending a bitmap, return the display to normal operation and display temperature?

**Comment by pvvx** [comment]
"60xxx...xxx" - output screen buffer "xx..xx" to LCD.
The screen buffer contains a bitmap of LCD segments.
"60" without data - disable this function.

But so far only the TH05F firmware disables the measurement output when the "60" function is displayed on the screen.

**Comment by dakhnod** [comment]
So, can I set a timeout for the bitmap?

**Comment by pvvx** [comment]
Not yet. -> _The function "22" will be added in the next version._
Any add-ons increase battery consumption. And not everyone needs such functions.
You are provided with source codes to create your own functions. Create what you need.

**Comment by dakhnod** [comment]
I understand, thanks for the discussion!

Speaking about the battery life, what is the expected battery life of the TH05F? That should be the V3.1, right?

**Comment by pvvx** [comment]
The functions "60" and "22" will be implemented in the coming days for all versions with LCD.

**Comment by dakhnod** [comment]
What is the expected battery life of the TH05F?

**Comment by pvvx** [comment]
More than 8 months and default settings and:
1. When using the cheapest CR2032 battery.
2. Without frequent connections to the device.
3. When the external adapter is operating in passive scanning mode.

**Comment by pvvx** [comment]
TH05F with CHT8305 transmits incorrect measurements when the battery voltage is below 2.5V. The CHT8305 sensor has a working voltage of up to 2.5V and is not suitable for use with CR2032.
![image](https://github.com/user-attachments/assets/8783e90c-4e6f-4b14-8939-ea3ece40c346)
Due to its low cost and simplified design, the use of CR2032 in Tuya thermometers is limited to 40% of the battery capacity.

**Comment by dakhnod** [comment]
How about the TH05Y_V3.1?

**Comment by pvvx** [comment]
The difference is not big. No more than 10%.
All claims to Tuya.

**Comment by dakhnod** [comment]
thanks tuya

**Comment by dakhnod** [comment]
So, turning off the LCD helps?

**Comment by pvvx** [comment]
By changing all settings it is possible to increase the operating time approximately twofold. But the dependence on the quality of the CR2032 battery is still greater.
If you modify the circuit to install the correct capacitor in the power supply, it will increase the operating time by 50%.

**Comment by pvvx** [comment]
MJWSD05MMMC (CR2450) when working in the "Le Long Range" mode (200 meters with obstacles). Consumption when transferred 6..8 times more (by transfer time, but not by power): 
![image](https://github.com/user-attachments/assets/2e7ba715-bb22-4e85-9d48-da248b6973c8)

**Comment by dakhnod** [comment]
> Le Long Range

LE coded?

**Comment by pvvx** [comment]
Comparison "LE Long Range" with WiFi.

Ble receiver - USB -BT RTL8761BU without an external antenna. Located in the house. The signal passes through 2 walls.
The Wi -fi router is in the attic, in direct sight with Wi -fi "Smart Plug".

WiFi "Smart Plug" and Th03z are located in one place in the garage. The outer wall of the garage is a thin metal sheet.
WiFi "Smart Plug" was chosen with the maximum quality of receipt and transmission of a dozen different ones. The rest of the "Smart Plug" did not support work at such a distance...
![image](https://github.com/user-attachments/assets/f30a30dc-7814-4a33-9a9b-3433f27587b1)

**Comment by dakhnod** [comment]
Should I just add a big enough capacitor to the battery in the thermometer? That should dampen the spikes, right?

**Comment by pvvx** [comment]
> Should I just add a big enough capacitor to the battery in the thermometer? That should dampen the spikes, right?

 https://github.com/user-attachments/files/18102754/swra349.pdf

**Comment by pvvx** [comment]
The "22" function has been added to the latest version 2.0.

![image](https://github.com/user-attachments/assets/bc851b4d-0bc3-4835-bfc8-207f43d23f03)

"227b002d003c0000" 
Show: 

12.3  
 45 

Display 60 seconds.
